Repository opensearch-project/opensearch-sdk-java, pull requests merged in 2023-07, with the labels that each got.

#861 Build fails due to transitive dependencies
  build.gradle
Labels: backport 1.x, first-time-contributor

#860 Updated Design diagram
  Docs/Extensions.png
Labels: backport 1.x, distinguished-contributor

#827 Register new routes via SDK as named routes
  CREATE_YOUR_FIRST_EXTENSION.md
  DEVELOPER_GUIDE.md
  PLUGIN_MIGRATION.md
  build.gradle
  config/certs/cert-gen.sh
  src/main/java/org/opensearch/sdk/ExtensionSettings.java
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/rest/BaseExtensionRestHandler.java
  src/main/java/org/opensearch/sdk/rest/ExtensionRestHandler.java
  src/main/java/org/opensearch/sdk/rest/ExtensionRestPathRegistry.java
  src/main/java/org/opensearch/sdk/rest/ReplacedRouteHandler.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestHelloAction.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestRemoteHelloAction.java
  src/test/java/org/opensearch/sdk/rest/TestBaseExtensionRestHandler.java
  src/test/java/org/opensearch/sdk/rest/TestExtensionRestPathRegistry.java
  src/test/java/org/opensearch/sdk/rest/TestNamedRouteHandler.java
  src/test/java/org/opensearch/sdk/sample/helloworld/rest/TestRestHelloAction.java
Labels: backport 1.x, first-time-contributor

#865 Add setup for GitHub pages
  _config.yml
  _includes/head_custom.html
  _includes/sidenav.html
  _layouts/default.html
  assets/css/style.scss
  assets/img/logo.png
Labels: first-time-contributor

#869 Update readme and more GitHub pages setup
  README.md
  _config.yml
  _includes/head_custom.html
  assets/img/favicon.ico
Labels: backport 1.x, repeat-contributor

#868 Makes route prefix setting `routeNamePrefix` optional
  DEVELOPER_GUIDE.md
  src/main/java/org/opensearch/sdk/ExtensionSettings.java
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/rest/BaseExtensionRestHandler.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestHelloAction.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestRemoteHelloAction.java
Labels: backport 1.x, repeat-contributor

#864 Add handlers for read, update, and delete to CREATE_YOUR_FIRST_EXTENSION doc
  CREATE_YOUR_FIRST_EXTENSION.md
Labels: backport 1.x, distinguished-contributor

#877 Revert "[Backport 1.x] Register new routes via SDK as named routes (#827) and Makes route prefix setting routeNamePrefix optional #868"
  CREATE_YOUR_FIRST_EXTENSION.md
  DEVELOPER_GUIDE.md
  PLUGIN_MIGRATION.md
  build.gradle
  config/certs/cert-gen.sh
  src/main/java/org/opensearch/sdk/ExtensionSettings.java
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/rest/BaseExtensionRestHandler.java
  src/main/java/org/opensearch/sdk/rest/ExtensionRestHandler.java
  src/main/java/org/opensearch/sdk/rest/ExtensionRestPathRegistry.java
  src/main/java/org/opensearch/sdk/rest/ReplacedRouteHandler.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestHelloAction.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestRemoteHelloAction.java
  src/test/java/org/opensearch/sdk/rest/TestBaseExtensionRestHandler.java
  src/test/java/org/opensearch/sdk/rest/TestExtensionRestPathRegistry.java
  src/test/java/org/opensearch/sdk/rest/TestNamedRouteHandler.java
  src/test/java/org/opensearch/sdk/sample/helloworld/rest/TestRestHelloAction.java
Labels: repeat-contributor

#880 Fixing imports
  src/main/java/org/opensearch/sdk/Extension.java
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/SDKNamedWriteableRegistry.java
  src/main/java/org/opensearch/sdk/action/RemoteExtensionActionRequest.java
  src/main/java/org/opensearch/sdk/api/SearchExtension.java
  src/main/java/org/opensearch/sdk/handlers/AcknowledgedResponseHandler.java
  src/main/java/org/opensearch/sdk/handlers/ClusterSettingsResponseHandler.java
  src/main/java/org/opensearch/sdk/handlers/ClusterStateResponseHandler.java
  src/main/java/org/opensearch/sdk/handlers/EnvironmentSettingsResponseHandler.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionActionRequestHandler.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionActionResponseHandler.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionDependencyResponseHandler.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsRestRequestHandler.java
  src/main/java/org/opensearch/sdk/rest/BaseExtensionRestHandler.java
  src/main/java/org/opensearch/sdk/rest/SDKHttpRequest.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestHelloAction.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestRemoteHelloAction.java
  src/main/java/org/opensearch/sdk/sample/helloworld/transport/SampleRequest.java
  src/main/java/org/opensearch/sdk/sample/helloworld/transport/SampleResponse.java
  src/main/java/org/opensearch/sdk/ssl/SSLNettyTransport.java
  src/main/java/org/opensearch/sdk/ssl/SecureSSLSettings.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
  src/test/java/org/opensearch/sdk/TestSDKNamedWriteableRegistry.java
  src/test/java/org/opensearch/sdk/TestSDKNamedXContentRegistry.java
  src/test/java/org/opensearch/sdk/action/TestProxyActionRequest.java
  src/test/java/org/opensearch/sdk/integTest/TransportCommunicationIT.java
  src/test/java/org/opensearch/sdk/rest/TestBaseExtensionRestHandler.java
  src/test/java/org/opensearch/sdk/rest/TestNamedRouteHandler.java
  src/test/java/org/opensearch/sdk/rest/TestSDKRestRequest.java
  src/test/java/org/opensearch/sdk/sample/helloworld/rest/TestRestHelloAction.java
  src/test/java/org/opensearch/sdk/sample/helloworld/transport/TestSampleAction.java
Labels: all-star-contributor

#874 Initial Hello World Extension integration test
  build.gradle
  src/test/java/org/opensearch/sdk/integTest/TransportCommunicationIT.java
  src/test/java/org/opensearch/sdk/sample/helloworld/rest/TestHelloWorldIT.java
Labels: backport 1.x, all-star-contributor

#882 Fix favicon link
  _includes/head_custom.html
Labels: backport 1.x, repeat-contributor

#883 Change link in favicon to relative
  _includes/head_custom.html
Labels: backport 1.x, repeat-contributor

#881 [Backport 1.x] Initial Hello World Extension integration test
  build.gradle
  src/test/java/org/opensearch/sdk/integTest/TransportCommunicationIT.java
  src/test/java/org/opensearch/sdk/sample/helloworld/rest/TestHelloWorldIT.java
Labels: all-star-contributor

#885 [Extensions] Allow default log4j behavior for users of SDK
  build.gradle
  src/main/resources/log4j2-sdk.xml
Labels: backport 1.x, repeat-contributor

#896 [1.x] Added snapshot check for build.gradle
  build.gradle
Labels: distinguished-contributor

#897 [1.x] Bumps SDK version
  build.gradle
Labels: distinguished-contributor

#900 Updated repository location on jenkins
  jenkins/release.jenkinsFile
Labels: backport 1.x, distinguished-contributor

#903 Updated POM publishing
  build.gradle
Labels: backport 1.x, distinguished-contributor, backport 0.1

#907 Update jenkins file to allow auto-publish
  jenkins/release.jenkinsFile
Labels: backport 1.x, repeat-contributor

#909 Updating experimental release version in dev docs
  DEVELOPER_GUIDE.md
Labels: backport 1.x, seasoned-contributor, backport 0.1

#912 Changed XContentType from MediaType
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestHelloAction.java
  src/test/java/org/opensearch/sdk/rest/TestSDKRestRequest.java
Labels: backport 1.x, distinguished-contributor, backport 0.1

#895 Added snapshot check for build.gradle
  build.gradle
Labels: distinguished-contributor
