Repository opensearch-project/opensearch-sdk-java, pull requests merged in 2023-05, with the labels that each got.

#619 Setup extension TLS
  Docs/CERTIFICATE_GENERATION.md
  src/main/java/org/opensearch/sdk/ExtensionSettings.java
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/NettyTransport.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsInitRequestHandler.java
  src/main/java/org/opensearch/sdk/ssl/DefaultSslKeyStore.java
  src/main/java/org/opensearch/sdk/ssl/SSLConfigConstants.java
  src/main/java/org/opensearch/sdk/ssl/SSLConnectionTestResult.java
  src/main/java/org/opensearch/sdk/ssl/SSLNettyTransport.java
  src/main/java/org/opensearch/sdk/ssl/SecureSSLSettings.java
  src/main/java/org/opensearch/sdk/ssl/SslKeyStore.java
  src/main/java/org/opensearch/sdk/ssl/util/CertFileProps.java
  src/main/java/org/opensearch/sdk/ssl/util/CertFromFile.java
  src/main/java/org/opensearch/sdk/ssl/util/CertFromKeystore.java
  src/main/java/org/opensearch/sdk/ssl/util/CertFromTruststore.java
  src/main/java/org/opensearch/sdk/ssl/util/ExceptionUtils.java
  src/main/java/org/opensearch/sdk/ssl/util/KeystoreProps.java
  src/main/java/org/opensearch/sdk/ssl/util/PemKeyReader.java
  src/main/java/org/opensearch/sdk/ssl/util/SSLCertificateHelper.java
  src/main/java/org/opensearch/sdk/ssl/util/Utils.java
  src/main/resources/sample/helloworld-settings.yml
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
Labels: backport 1.x, first-time-contributor

#717 Updates migration doc for ParsedMax
  PLUGIN_MIGRATION.md
Labels: backport 1.x, distinguished-contributor

#718 [Backport 1.x] Setup extension TLS
  Docs/CERTIFICATE_GENERATION.md
  src/main/java/org/opensearch/sdk/ExtensionSettings.java
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/NettyTransport.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsInitRequestHandler.java
  src/main/java/org/opensearch/sdk/ssl/DefaultSslKeyStore.java
  src/main/java/org/opensearch/sdk/ssl/SSLConfigConstants.java
  src/main/java/org/opensearch/sdk/ssl/SSLConnectionTestResult.java
  src/main/java/org/opensearch/sdk/ssl/SSLNettyTransport.java
  src/main/java/org/opensearch/sdk/ssl/SecureSSLSettings.java
  src/main/java/org/opensearch/sdk/ssl/SslKeyStore.java
  src/main/java/org/opensearch/sdk/ssl/util/CertFileProps.java
  src/main/java/org/opensearch/sdk/ssl/util/CertFromFile.java
  src/main/java/org/opensearch/sdk/ssl/util/CertFromKeystore.java
  src/main/java/org/opensearch/sdk/ssl/util/CertFromTruststore.java
  src/main/java/org/opensearch/sdk/ssl/util/ExceptionUtils.java
  src/main/java/org/opensearch/sdk/ssl/util/KeystoreProps.java
  src/main/java/org/opensearch/sdk/ssl/util/PemKeyReader.java
  src/main/java/org/opensearch/sdk/ssl/util/SSLCertificateHelper.java
  src/main/java/org/opensearch/sdk/ssl/util/Utils.java
  src/main/resources/sample/helloworld-settings.yml
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
Labels: first-time-contributor

#727 Fixed gradlew run without security
  DEVELOPER_GUIDE.md
  src/main/resources/sample/helloworld-settings.yml
Labels: backport 1.x, distinguished-contributor

#733 [CCI] Added @return to javadoc for MapperExtension class
  src/main/java/org/opensearch/sdk/api/MapperExtension.java
Labels: backport 1.x, CCI, valued-contributor

#735 Added return notation to javadoc of extension interfaces
  src/main/java/org/opensearch/sdk/api/AnalysisExtension.java
  src/main/java/org/opensearch/sdk/api/CircuitBreakerExtension.java
Labels: backport 1.x, CCI, repeat-contributor

#741 Adding updateSettings to sdk cluster admin client
  src/main/java/org/opensearch/sdk/SDKClient.java
  src/test/java/org/opensearch/sdk/TestSDKClient.java
Labels: backport 1.x, seasoned-contributor

#736 Added method for create OK status response with empty JSON content
  src/main/java/org/opensearch/sdk/rest/BaseExtensionRestHandler.java
  src/test/java/org/opensearch/sdk/rest/TestBaseExtensionRestHandler.java
Labels: backport 1.x, CCI, repeat-contributor

#743 Adding cross-version support for extension transport apis
  src/main/java/org/opensearch/sdk/SDKTransportService.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionActionRequestHandler.java
Labels: backport 1.x, seasoned-contributor

#747 Fixed docs for new api changes
  CREATE_YOUR_FIRST_EXTENSION.md
Labels: backport 1.x, valued-contributor

#745 Replaced implementation() by api() for opensearch libs
  build.gradle
Labels: backport 1.x, CCI, valued-contributor

#752 Added missed javadoc for ActionExtension, CertFileProps
  src/main/java/org/opensearch/sdk/api/ActionExtension.java
  src/main/java/org/opensearch/sdk/ssl/util/CertFileProps.java
Labels: backport 1.x, CCI, valued-contributor

#751 [Backport 1.x] Replaced implementation() by api() for opensearch libs
  build.gradle
Labels: distinguished-contributor

#753 [CCI] Add javadoc to ExtensionSettings and ExtensionRunner class
  src/main/java/org/opensearch/sdk/ExtensionSettings.java
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
Labels: backport 1.x, CCI, valued-contributor

#755 Add dependency information to from-scratch docs
  CREATE_YOUR_FIRST_EXTENSION.md
Labels: backport 1.x, distinguished-contributor

#764 [Extensions] Fixing Imports String.java
  src/main/java/org/opensearch/sdk/api/ActionExtension.java
  src/main/java/org/opensearch/sdk/ssl/util/SSLCertificateHelper.java
Labels: backport 1.x, repeat-contributor

#763 Add default Opensearch host and port if init comes from localhost
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsInitRequestHandler.java
  src/main/resources/sample/helloworld-settings.yml
  src/test/java/org/opensearch/sdk/ExtensionsRunnerForTest.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
  src/test/java/org/opensearch/sdk/sample/helloworld/TestHelloWorldExtension.java
Labels: backport 1.x, distinguished-contributor

#778 Removed handler for onIndexModule
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
Labels: backport 1.x, distinguished-contributor

#783 Revert "Add default Opensearch host and port if init comes from localhost (#763)"
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsInitRequestHandler.java
  src/main/resources/sample/helloworld-settings.yml
  src/test/java/org/opensearch/sdk/ExtensionsRunnerForTest.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
  src/test/java/org/opensearch/sdk/sample/helloworld/TestHelloWorldExtension.java
Labels: backport 1.x, seasoned-contributor

#784 Revert "[Backport 1.x] Add default Opensearch host and port if init comes from localhost (#770)"
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsInitRequestHandler.java
  src/main/resources/sample/helloworld-settings.yml
  src/test/java/org/opensearch/sdk/ExtensionsRunnerForTest.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
  src/test/java/org/opensearch/sdk/sample/helloworld/TestHelloWorldExtension.java
Labels: seasoned-contributor

#786 Don't change Extension REST client Settings with transport node info
  src/main/java/org/opensearch/sdk/handlers/ExtensionsInitRequestHandler.java
Labels: backport 1.x, distinguished-contributor

#788 Update SDKRestClient/OpenSearchAsync client with http.port setting from OpenSearch during intialization
  src/main/java/org/opensearch/sdk/SDKClient.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsInitRequestHandler.java
  src/test/java/org/opensearch/sdk/sample/helloworld/TestHelloWorldExtension.java
Labels: backport 1.x, seasoned-contributor

#687 Add integration test framework
  DEVELOPER_GUIDE.md
  build.gradle
  src/main/resources/sample/helloworld-settings.yml
  src/test/java/org/opensearch/sdk/integTest/TransportCommunicationIT.java
  src/test/resources/hello-world-extension.yml
Labels: backport 1.x, seasoned-contributor
