Repository opensearch-project/opensearch-sdk-java, pull requests merged in 2023-06, with the labels that each got.

#800 Fix publishing
  build.gradle
Labels: backport 1.x, seasoned-contributor

#802 Adds exists/aliasExists() methods to SDKIndicesClient
  src/main/java/org/opensearch/sdk/SDKClient.java
  src/test/java/org/opensearch/sdk/TestSDKClient.java
Labels: backport 1.x, all-star-contributor

#804 Fix publishing to sonatype
  build.gradle
Labels: backport 1.x, seasoned-contributor

#807 Fix Maven Local Publishing
  build.gradle
Labels: backport 1.x, seasoned-contributor

#806 Added Publish to Maven Local check before build
  .github/workflows/build.yml
Labels: backport 1.x, distinguished-contributor

#777 Refactor extension documentation
  CREATE_YOUR_FIRST_EXTENSION.md
  DESIGN.md
  DEVELOPER_GUIDE.md
  PLUGIN_MIGRATION.md
  README.md
  src/main/java/org/opensearch/sdk/sample/helloworld/HelloWorldExtension.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestRemoteHelloAction.java
Labels: backport 1.x, first-time-contributor

#809 Add changes made in 1.x for manual backport
  build.gradle
Labels: all-star-contributor

#813 [Backport 1.x] Refactored all sendFooRequest(TransportService transportService) calls
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/SDKClusterService.java
  src/main/java/org/opensearch/sdk/SDKTransportService.java
  src/main/java/org/opensearch/sdk/handlers/ClusterSettingsResponseHandler.java
  src/main/java/org/opensearch/sdk/handlers/ClusterStateResponseHandler.java
  src/main/java/org/opensearch/sdk/handlers/EnvironmentSettingsResponseHandler.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionDependencyResponseHandler.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsInitRequestHandler.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
  src/test/java/org/opensearch/sdk/TestSDKClusterService.java
  src/test/java/org/opensearch/sdk/action/TestProxyActionRequest.java
Labels: distinguished-contributor

#818 Adds ClusterName to SDKClusterService
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/SDKClusterService.java
  src/test/java/org/opensearch/sdk/TestSDKClusterService.java
Labels: backport 1.x, all-star-contributor

#816 [Backport-1.x] Refactor extension documentation (#777) backport to 1.x
  CREATE_YOUR_FIRST_EXTENSION.md
  DESIGN.md
  DEVELOPER_GUIDE.md
  PLUGIN_MIGRATION.md
  README.md
  src/main/java/org/opensearch/sdk/sample/helloworld/HelloWorldExtension.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestRemoteHelloAction.java
Labels: first-time-contributor

#822 Add javadoc task to enable automatic javadoc publishing
  build.gradle
Labels: backport 1.x, all-star-contributor

#825 Update outdated class names in documentation
  Docs/ExtensionRestActions.svg
Labels: backport 1.x, all-star-contributor

#830 fix(bug): Extension should not bind to its hostname
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
Labels: backport 1.x, first-time-contributor

#820 Updated DEV guide with the new initialization api
  DEVELOPER_GUIDE.md
Labels: backport 1.x

#837 Added release drafter for one click release of SDK
  .github/workflows/release-drafter.yml
  build.gradle
Labels: backport 1.x, distinguished-contributor

#841 [Backport-1.x] Added release drafter for one click release of SDK
  .github/workflows/release-drafter.yml
  build.gradle
Labels: distinguished-contributor

#840 Added Jenkins file and RELEASING.md
  RELEASING.md
  jenkins/release.jenkinsFile
Labels: backport 1.x, distinguished-contributor

#845 Updated DESIGN.md and the extension design architecture.
  DESIGN.md
  Docs/Extensions.png
Labels: backport 1.x, distinguished-contributor

#842 Bind Extension host to wildcard address
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
Labels: backport 1.x, distinguished-contributor

#850 Forced slf4j dependency to 1.7.36
  build.gradle
Labels: backport 1.x, distinguished-contributor
