Repository opensearch-project/opensearch-sdk-java, pull requests merged in 2023-03, with the labels that each got.

#504 Removing SafeConstructor() now that Snakeyml has been bumped up to 2.0
  src/main/java/org/opensearch/sdk/ExtensionSettings.java
Labels: backport 1.x

#506 Update PLUGIN_MIGRATION document with guidance on how to retrieve NamedXContentRegistry objects for created components
  PLUGIN_MIGRATION.md
Labels: backport 1.x

#510 Delay sending Settings Update Consumers until initialization
  src/main/java/org/opensearch/sdk/SDKClusterService.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsInitRequestHandler.java
  src/test/java/org/opensearch/sdk/TestSDKClusterService.java
Labels: backport 1.x

#515 Added updateSettings for SDKIndicesClient
  src/main/java/org/opensearch/sdk/SDKClient.java
  src/test/java/org/opensearch/sdk/TestSDKClient.java
Labels: backport 1.x

#520 Properly initialize SDKClient actions map
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/SDKClient.java
  src/test/java/org/opensearch/sdk/sample/helloworld/TestHelloWorldExtension.java
Labels: backport 1.x

#517 Whitesource remediate/gradle 8.x
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: backport 1.x

#524 Only store names of extension transport actions
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/TransportActions.java
  src/main/java/org/opensearch/sdk/action/SDKActionModule.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsInitRequestHandler.java
  src/test/java/org/opensearch/sdk/action/TestSDKActionModule.java
Labels: backport 1.x

#529 Add empty or custom SDKNamedXContentRegistry
  src/main/java/org/opensearch/sdk/SDKNamedXContentRegistry.java
  src/test/java/org/opensearch/sdk/TestSDKNamedXContentRegistry.java
Labels: backport 1.x

#508 Added Changes on SDK Side to register its Implemented Interfaces
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsInitRequestHandler.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
Labels: backport 1.x

#537 Always initialize SDKActionModule
  src/main/java/org/opensearch/sdk/BaseExtension.java
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/SDKClient.java
  src/main/java/org/opensearch/sdk/action/SDKActionModule.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsInitRequestHandler.java
  src/main/java/org/opensearch/sdk/sample/helloworld/HelloWorldExtension.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
  src/test/java/org/opensearch/sdk/action/TestSDKActionModule.java
  src/test/java/org/opensearch/sdk/sample/helloworld/TestHelloWorldExtension.java
Labels: backport 1.x

#534 Created ScriptExtension interface #318
  src/main/java/org/opensearch/sdk/ScriptExtension.java
  src/test/java/org/opensearch/sdk/TestExtensionInterfaces.java
Labels: backport 1.x

#421 Add sample for validator
  src/main/java/org/opensearch/sdk/sample/helloworld/ExampleCustomSettingConfig.java
  src/main/java/org/opensearch/sdk/sample/helloworld/HelloWorldExtension.java
  src/test/java/org/opensearch/sdk/sample/helloworld/TestHelloWorldExtension.java
Labels: backport 1.x

#551 Use checkstyle for javadoc checks
  build.gradle
  config/checkstyle/checkstyle.xml
  config/checkstyle/checkstyle_suppressions.xml
  gradle/formatting.gradle
  src/main/java/org/opensearch/sdk/ActionExtension.java
  src/main/java/org/opensearch/sdk/BaseExtensionRestHandler.java
  src/main/java/org/opensearch/sdk/EngineExtension.java
  src/main/java/org/opensearch/sdk/SDKClient.java
  src/main/java/org/opensearch/sdk/SearchExtension.java
Labels: backport 1.x

#558 Integrated Async Java Client
  src/main/java/org/opensearch/sdk/SDKClient.java
  src/test/java/org/opensearch/sdk/TestSDKClient.java
Labels: backport 1.x

#546 Created the MapperExtension interface and added the MapperPlugin content
  src/main/java/org/opensearch/sdk/MapperExtension.java
  src/test/java/org/opensearch/sdk/TestExtensionInterfaces.java
Labels: backport 1.x

#560 Remove unneeded banch deletion workflow
  .github/workflows/delete_backport_branch.yml
Labels: backport 1.x

#543 Added IndexStoreExtension interface
  src/main/java/org/opensearch/sdk/IndexStoreExtension.java
  src/test/java/org/opensearch/sdk/TestExtensionInterfaces.java
Labels: backport 1.x

#559 Change SDKClusterSettings constructor to use same params as ClusterSettings
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/SDKClusterService.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsInitRequestHandler.java
  src/test/java/org/opensearch/sdk/TestSDKClusterService.java
Labels: backport 1.x

#572 Added SystemIndexExtension
  src/main/java/org/opensearch/sdk/SystemIndexExtension.java
  src/test/java/org/opensearch/sdk/TestExtensionInterfaces.java
Labels: backport 1.x

#562 Add PersistentTaskExtension interface
  src/main/java/org/opensearch/sdk/PersistentTaskExtension.java
  src/test/java/org/opensearch/sdk/TestExtensionInterfaces.java
Labels: backport 1.x

#577 Added github-merit-badger for SDK
  .github/workflows/github-merit-badger.yml
Labels: backport 1.x

#579 Initialize SDKClient with instance of ExtensionSettings
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/SDKClient.java
  src/test/java/org/opensearch/sdk/TestSDKClient.java
  src/test/java/org/opensearch/sdk/sample/helloworld/TestHelloWorldExtension.java
Labels: backport 1.x

#575 [FEATURE] Create ReloadableExtension interface
  src/main/java/org/opensearch/sdk/ReloadableExtension.java
Labels: backport 1.x

#582 Miscellaneous Spotbugs issues
  src/main/java/org/opensearch/sdk/handlers/ExtensionDependencyResponseHandler.java
  src/test/java/org/opensearch/sdk/ExtensionsRunnerForTest.java
  src/test/java/org/opensearch/sdk/TestBaseExtension.java
  src/test/java/org/opensearch/sdk/TestExtensionRestHandler.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
  src/test/java/org/opensearch/sdk/TransportCommunicationIT.java
Labels: backport 1.x

#586 Created Repository Extension
  src/main/java/org/opensearch/sdk/RepositoryExtension.java
  src/test/java/org/opensearch/sdk/TestExtensionInterfaces.java
Labels: backport 1.x

#597 Added CircuitBreakerExtension interface
  src/main/java/org/opensearch/sdk/CircuitBreakerExtension.java
  src/test/java/org/opensearch/sdk/TestExtensionInterfaces.java
Labels: backport 1.x, first-time-contributor

#588 Execute remote actions on another extension
  DESIGN.md
  Docs/RemoteActionExecution.svg
  src/main/java/org/opensearch/sdk/BaseExtension.java
  src/main/java/org/opensearch/sdk/Extension.java
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/SDKClient.java
  src/main/java/org/opensearch/sdk/SDKTransportService.java
  src/main/java/org/opensearch/sdk/action/RemoteExtensionAction.java
  src/main/java/org/opensearch/sdk/action/RemoteExtensionActionRequest.java
  src/main/java/org/opensearch/sdk/action/RemoteExtensionTransportAction.java
  src/main/java/org/opensearch/sdk/action/SDKActionModule.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionActionRequestHandler.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionActionResponseHandler.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsInitRequestHandler.java
  src/main/java/org/opensearch/sdk/sample/helloworld/HelloWorldExtension.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestRemoteHelloAction.java
  src/test/java/org/opensearch/sdk/TestExtensionInterfaces.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
  src/test/java/org/opensearch/sdk/TestSDKTransportService.java
  src/test/java/org/opensearch/sdk/action/TestProxyActionRequest.java
  src/test/java/org/opensearch/sdk/action/TestSDKActionModule.java
  src/test/java/org/opensearch/sdk/sample/helloworld/TestHelloWorldExtension.java
Labels: backport 1.x

#553 Added getNamedWriteableRegistry() API for extensions
  src/main/java/org/opensearch/sdk/BaseExtension.java
  src/main/java/org/opensearch/sdk/Extension.java
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/NettyTransport.java
  src/main/java/org/opensearch/sdk/SDKNamedWriteableRegistry.java
  src/test/java/org/opensearch/sdk/TestSDKNamedWriteableRegistry.java
Labels: backport 1.x, CCI

#618 [Backport 1.x] Change imports for xcontent
  src/main/java/org/opensearch/sdk/Extension.java
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/RepositoryExtension.java
  src/main/java/org/opensearch/sdk/SDKNamedXContentRegistry.java
  src/main/java/org/opensearch/sdk/SearchExtension.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestHelloAction.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
  src/test/java/org/opensearch/sdk/TestSDKNamedXContentRegistry.java
Labels: seasoned-contributor

#627 Adds getExecutorBuilders and indexNameExpressionResolver to extensionsRunner
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
Labels: backport 1.x, seasoned-contributor

#623 Generate RestRequest to pass to Rest Handlers
  PLUGIN_MIGRATION.md
  src/main/java/org/opensearch/sdk/BaseExtensionRestHandler.java
  src/main/java/org/opensearch/sdk/ExtensionRestHandler.java
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/RouteHandler.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsRestRequestHandler.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestHelloAction.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestRemoteHelloAction.java
  src/test/java/org/opensearch/sdk/TestBaseExtensionRestHandler.java
  src/test/java/org/opensearch/sdk/TestExtensionRestHandler.java
  src/test/java/org/opensearch/sdk/TestExtensionRestPathRegistry.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
  src/test/java/org/opensearch/sdk/sample/helloworld/rest/TestRestHelloAction.java
Labels: backport 1.x, distinguished-contributor

#628 [Backport 1.x] Adds getExecutorBuilders and indexNameExpressionResolver to extensionsRunner
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/SDKNamedXContentRegistry.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
Labels: seasoned-contributor
