Repository opensearch-project/opensearch-sdk-java, pull requests merged in 2023-04, with the labels that each got.

#600 Created ExtensibleExtension interface
  src/main/java/org/opensearch/sdk/ExtensibleExtension.java
Labels: backport 1.x, CCI, first-time-contributor

#630 [Backport 1.x] Generate RestRequest to pass to Rest Handlers
  PLUGIN_MIGRATION.md
  src/main/java/org/opensearch/sdk/BaseExtensionRestHandler.java
  src/main/java/org/opensearch/sdk/ExtensionRestHandler.java
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/RouteHandler.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsRestRequestHandler.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestHelloAction.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestRemoteHelloAction.java
  src/test/java/org/opensearch/sdk/TestBaseExtensionRestHandler.java
  src/test/java/org/opensearch/sdk/TestExtensionRestHandler.java
  src/test/java/org/opensearch/sdk/TestExtensionRestPathRegistry.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
  src/test/java/org/opensearch/sdk/sample/helloworld/rest/TestRestHelloAction.java
Labels: distinguished-contributor

#645 Adding performRequestAsync to SDKRestClient
  src/main/java/org/opensearch/sdk/SDKClient.java
  src/test/java/org/opensearch/sdk/TestSDKClient.java
Labels: backport 1.x, seasoned-contributor

#650 Move all the extensions interface under a same directory
  CREATE_YOUR_FIRST_EXTENSION.md
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/SDKTransportService.java
  src/main/java/org/opensearch/sdk/action/SDKActionModule.java
  src/main/java/org/opensearch/sdk/api/ActionExtension.java
  src/main/java/org/opensearch/sdk/api/AnalysisExtension.java
  src/main/java/org/opensearch/sdk/api/CircuitBreakerExtension.java
  src/main/java/org/opensearch/sdk/api/EngineExtension.java
  src/main/java/org/opensearch/sdk/api/ExtensibleExtension.java
  src/main/java/org/opensearch/sdk/api/IndexStoreExtension.java
  src/main/java/org/opensearch/sdk/api/IngestExtension.java
  src/main/java/org/opensearch/sdk/api/MapperExtension.java
  src/main/java/org/opensearch/sdk/api/PersistentTaskExtension.java
  src/main/java/org/opensearch/sdk/api/ReloadableExtension.java
  src/main/java/org/opensearch/sdk/api/RepositoryExtension.java
  src/main/java/org/opensearch/sdk/api/ScriptExtension.java
  src/main/java/org/opensearch/sdk/api/SearchExtension.java
  src/main/java/org/opensearch/sdk/api/SystemIndexExtension.java
  src/main/java/org/opensearch/sdk/sample/helloworld/HelloWorldExtension.java
  src/test/java/org/opensearch/sdk/TestExtensionInterfaces.java
  src/test/java/org/opensearch/sdk/action/TestSDKActionModule.java
  src/test/java/org/opensearch/sdk/sample/helloworld/TestHelloWorldExtension.java
Labels: backport 1.x, CCI, first-time-contributor

#660 [1.x] Catch up backports
  CREATE_YOUR_FIRST_EXTENSION.md
  build.gradle
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/SDKTransportService.java
  src/main/java/org/opensearch/sdk/action/SDKActionModule.java
  src/main/java/org/opensearch/sdk/api/ActionExtension.java
  src/main/java/org/opensearch/sdk/api/AnalysisExtension.java
  src/main/java/org/opensearch/sdk/api/CircuitBreakerExtension.java
  src/main/java/org/opensearch/sdk/api/EngineExtension.java
  src/main/java/org/opensearch/sdk/api/ExtensibleExtension.java
  src/main/java/org/opensearch/sdk/api/IndexStoreExtension.java
  src/main/java/org/opensearch/sdk/api/IngestExtension.java
  src/main/java/org/opensearch/sdk/api/MapperExtension.java
  src/main/java/org/opensearch/sdk/api/PersistentTaskExtension.java
  src/main/java/org/opensearch/sdk/api/ReloadableExtension.java
  src/main/java/org/opensearch/sdk/api/RepositoryExtension.java
  src/main/java/org/opensearch/sdk/api/ScriptExtension.java
  src/main/java/org/opensearch/sdk/api/SearchExtension.java
  src/main/java/org/opensearch/sdk/api/SystemIndexExtension.java
  src/main/java/org/opensearch/sdk/sample/helloworld/HelloWorldExtension.java
  src/test/java/org/opensearch/sdk/TestExtensionInterfaces.java
  src/test/java/org/opensearch/sdk/action/TestSDKActionModule.java
  src/test/java/org/opensearch/sdk/sample/helloworld/TestHelloWorldExtension.java
Labels: distinguished-contributor

#643 Added support for headers for ExtensionRestRequest
  src/main/java/org/opensearch/sdk/handlers/ExtensionsRestRequestHandler.java
  src/main/java/org/opensearch/sdk/rest/SDKHttpRequest.java
  src/main/java/org/opensearch/sdk/rest/SDKRestRequest.java
  src/test/java/org/opensearch/sdk/TestBaseExtensionRestHandler.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
  src/test/java/org/opensearch/sdk/rest/TestSDKRestRequest.java
  src/test/java/org/opensearch/sdk/sample/helloworld/rest/TestRestHelloAction.java
Labels: backport 1.x, CCI, repeat-contributor

#661 Revert "Update VachaShah/backport action to v2.2.0"
  .github/workflows/backport.yml
Labels: backport 1.x, all-star-contributor

#608 Changed the test for RegexValidator class
  src/main/java/org/opensearch/sdk/sample/helloworld/ExampleCustomSettingConfig.java
  src/test/java/org/opensearch/sdk/sample/helloworld/TestHelloWorldExtension.java
Labels: backport 1.x, CCI, repeat-contributor

#658 Match Rest Path registry with RestController using SDKMethodHandlers
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsRestRequestHandler.java
  src/main/java/org/opensearch/sdk/rest/ExtensionRestPathRegistry.java
  src/main/java/org/opensearch/sdk/rest/SDKMethodHandlers.java
  src/test/java/org/opensearch/sdk/TestExtensionRestPathRegistry.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
Labels: backport 1.x, distinguished-contributor

#664 [Backport 1.x] Match Rest Path registry with RestController using SDKMethodHandlers
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsRestRequestHandler.java
  src/main/java/org/opensearch/sdk/rest/ExtensionRestPathRegistry.java
  src/main/java/org/opensearch/sdk/rest/SDKMethodHandlers.java
  src/test/java/org/opensearch/sdk/TestExtensionRestPathRegistry.java
  src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
Labels: distinguished-contributor

#522 Removed old addSettingsUpdateConsumer method
  src/main/java/org/opensearch/sdk/SDKClusterService.java
  src/test/java/org/opensearch/sdk/TestSDKClusterService.java
Labels: backport 1.x, CCI

#670 Adding unrecognized method in BaseExtensionRestHandler
  src/main/java/org/opensearch/sdk/BaseExtensionRestHandler.java
Labels: backport 1.x, repeat-contributor

#613 Add identity/authorization headers into Rest Client calls
  src/main/java/org/opensearch/sdk/SDKClient.java
Labels: backport 1.x, CCI, first-time-contributor

#673 Updates PLUGIN_MIGRATION.md for aggregation return type
  PLUGIN_MIGRATION.md
Labels: backport 1.x, all-star-contributor

#657 Update dev guide to add another option to run OpenSearch with Extensions feature-flag enable
  DEVELOPER_GUIDE.md
Labels: backport 1.x, first-time-contributor

#666 Handle Deprecated and Replaced Routes in Extension Rest Handlers
  src/main/java/org/opensearch/sdk/BaseExtensionRestHandler.java
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
  src/main/java/org/opensearch/sdk/RouteHandler.java
  src/main/java/org/opensearch/sdk/api/ActionExtension.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsRestRequestHandler.java
  src/main/java/org/opensearch/sdk/rest/BaseExtensionRestHandler.java
  src/main/java/org/opensearch/sdk/rest/ExtensionRestHandler.java
  src/main/java/org/opensearch/sdk/rest/ExtensionRestPathRegistry.java
  src/main/java/org/opensearch/sdk/rest/ReplacedRouteHandler.java
  src/main/java/org/opensearch/sdk/rest/SDKMethodHandlers.java
  src/main/java/org/opensearch/sdk/sample/helloworld/HelloWorldExtension.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestHelloAction.java
  src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestRemoteHelloAction.java
  src/test/java/org/opensearch/sdk/TestBaseExtensionRestHandler.java
  src/test/java/org/opensearch/sdk/TestExtensionRestPathRegistry.java
  src/test/java/org/opensearch/sdk/rest/TestBaseExtensionRestHandler.java
  src/test/java/org/opensearch/sdk/rest/TestExtensionRestHandler.java
  src/test/java/org/opensearch/sdk/rest/TestExtensionRestPathRegistry.java
  src/test/java/org/opensearch/sdk/sample/helloworld/TestHelloWorldExtension.java
  src/test/java/org/opensearch/sdk/sample/helloworld/rest/TestRestHelloAction.java
Labels: backport 1.x, distinguished-contributor

#672 Implement getFieldMapping on SDKRestClient
  PLUGIN_MIGRATION.md
  src/main/java/org/opensearch/sdk/SDKClient.java
  src/test/java/org/opensearch/sdk/TestSDKClient.java
Labels: backport 1.x, distinguished-contributor

#647 Companion changes for moving ExtensionRequest to Protobuf
  src/main/java/org/opensearch/sdk/ExtensionsRunner.java
Labels: backport 1.x, seasoned-contributor

#690 Adds bulk request for SDKRestClient
  src/main/java/org/opensearch/sdk/SDKClient.java
  src/test/java/org/opensearch/sdk/TestSDKClient.java
Labels: backport 1.x, seasoned-contributor

#696 Fix javadoc links
  src/main/java/org/opensearch/sdk/handlers/ExtensionActionRequestHandler.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionActionResponseHandler.java
  src/main/java/org/opensearch/sdk/rest/BaseExtensionRestHandler.java
Labels: backport 1.x, distinguished-contributor

#697 Fix javadocs and improve javadoc CI
  .github/workflows/build.yml
  src/main/java/org/opensearch/sdk/handlers/ExtensionActionRequestHandler.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionActionResponseHandler.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsRestRequestHandler.java
Labels: backport 1.x, distinguished-contributor

#701 [Backport 1.x] Fix javadocs and improve javadoc CI
  .github/workflows/build.yml
  src/main/java/org/opensearch/sdk/handlers/ExtensionActionRequestHandler.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionActionResponseHandler.java
  src/main/java/org/opensearch/sdk/handlers/ExtensionsRestRequestHandler.java
Labels: distinguished-contributor

#708 Adds DeleteByQuery Request for SDKRestClient
  src/main/java/org/opensearch/sdk/SDKClient.java
  src/test/java/org/opensearch/sdk/TestSDKClient.java
Labels: backport 1.x, distinguished-contributor

#713 Updates delete by query method
  src/main/java/org/opensearch/sdk/SDKClient.java
  src/test/java/org/opensearch/sdk/TestSDKClient.java
Labels: backport 1.x, distinguished-contributor
