Repository opensearch-project/opensearch-sdk-java, pull requests merged in 2024-01, with the labels that each got.

#979 Added IndicesService in Parameters to fix test
  src/test/java/org/opensearch/sdk/TestExtensionInterfaces.java
Labels: backport 1.x, distinguished-contributor

#982 Fixing initialize test extension as jackson version mismatch with core.
  build.gradle
Labels: backport 1.x, seasoned-contributor

#978 Switch to more reliable OpenSearch Lucene snapshot location
  CREATE_YOUR_FIRST_EXTENSION.md
  build.gradle
Labels: backport 1.x, first-time-contributor
